# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not
# exceed four million.
#
# 4613732
a, b, sum = 1, 2, 0
while b < 4000000
  sum = sum + b if b.modulo(2) == 0
  a, b = b, a + b
end

puts "Sum of even fibs for fib(4000000): #{sum}"
